-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'AD_SLOT_BOOKED';
ALTER TYPE "NotificationType" ADD VALUE 'AD_SLOT_PUBLISHED';
ALTER TYPE "NotificationType" ADD VALUE 'AD_SLOT_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE 'AD_SLOT_REFUNDED';
ALTER TYPE "NotificationType" ADD VALUE 'AD_SLOT_AVAILABLE';
